time_range:
  start_date: "2021-01-01"
  end_date: "2026-01-01"

companies:
  - company: JYP
    ticker: "035900.KQ"
    groups:
      - TWICE
  - company: SM
    ticker: "041510.KQ"
    groups:
      - aespa
  - company: YG
    ticker: "122870.KQ"
    groups:
      - BLACKPINK
  - company: HYBE
    ticker: "352820.KS"
    groups:
      - NewJeans
      - LE SSERAFIM
